[package]
name = "rust-align-128"
version = "0.1.0"
edition = "2021"


[dependencies]

[dev-dependencies]
criterion = { package = "codspeed-criterion-compat", version = "2.6.0" }
rand = "0.8.5"
type-layout = "0.2.0"

[[bench]]
name = "benches"
harness = false
path = "benches.rs"
